#! /usr/bin/env escript
%% -*- erlang -*-
%%! -smp enable -detached -pa /home/hakan/erl_libs/eflex/ebin

main([]) ->
    eflex:start();
main(["--help"]) ->
    AppDir = get_app_dir(),
    File = filename:join([AppDir, "README"]),
    case file:read_file(File) of
	{ok, Bin} ->
	    io:format("~s\n", [binary_to_list(Bin)]);
	{error, Reason} ->
	    io:format("~s: ~s\n", [File, file:format_error(Reason)]),
	    halt(3)
    end;
main(_) ->
    usage().

usage() ->
    FullName = escript:script_name(),
    BaseName = filename:basename(FullName),
    io:format("usage: ~s [--help]\n", [BaseName]),
    halt(1).

get_app_dir() ->
    case code:lib_dir(eflex) of
	{error, Reason} ->
	    io:format("Illegal application directory: ~p\n", [Reason]),
	    halt(2);
	AppDir ->
	    AppDir
    end.
