(setq mew-config-alist '(
         ("default"
         ("name"         .  "z_axis")
         ("user"         .  "z_axis")
         ("smtp-server"  .  "smtp.163.com")
         ("smtp-port"    .  "25")
         ("pop-server"   .  "pop.163.com")
         ("pop-port"     .  "110")
         ("smtp-user"    .  "z_axis")
         ("pop-user"     .  "z_axis")
         ("mail-domain"  .  "163.com")
         ("mailbox-type" .  pop)
         ("pop-auth"     .  pass)
         ("smtp-auth-list" . ("PLAIN" "LOGIN" "CRAM-MD5"))
         )
         ("czsq"
         ("name"         .  "czsq888")
         ("user"         .  "czsq888")
         ("smtp-server"  .  "smtp.163.com")
         ("smtp-port"    .  "25")
         ("pop-server"   .  "pop.163.com")
         ("pop-port"     .  "110")
         ("smtp-user"    .  "czsq888")
         ("pop-user"     .  "czsq888")
         ("mail-domain"  .  "163.com")
         ("mailbox-type" .  pop)
         ("pop-auth"     .  pass)
         ("smtp-auth-list" . ("PLAIN" "LOGIN" "CRAM-MD5"))
         )
 ))
(setq mew-ssl-verify-level 0)
