(autoload 'mew "mew" nil t) 
(autoload 'mew-send "mew" nil t) 
(setq mew-use-cached-passwd t) 
(setq mew-pop-size 0) 
(setq mew-pop-delete nil) 
(setq mew-config-alist 
'(("default" 
    ("name" . "多行") 
    ("user" . "sw2wolf") 
    ("mail-domain" . "163.com") 
    ("pop-server" . "pop3.163.com") 
    ("pop-port" . "110") 
    ("pop-user" . "sw2wolf") 
    ("pop-auth" . "*********") 
    ("smtp-server" . "smtp.163.com") 
    ("smtp-port" . "25") 
    ("smtp-user" . "sw2wolf") 
    ("smtp-auth-list" . ("CRAM-MD5" "LOGIN" "PLAIN")))))
