#!/bin/sh
#
# $FreeBSD: ports/lang/clojure/files/clojure-bin.in,v 1.9 2012/06/19 05:38:12 glewis Exp $

breakchars="(){}[],^%$#@\"\";:''|\\"
MYCP="/media/D/www/qachina/db/doc/clojure/"

CP="$HOME/clojure-1.4.0/clojure-1.4.0.jar:$MYCP:$CLASSPATH" 

cd "/media/D/www/qachina/db/doc/clojure"
echo $CP
rlwrap --remember -c -b "$breakchars" -f "$HOME"/.clj_completions \
    /usr/local/bin/java -cp $CP clojure.main -i ~/.clojurerc -r "$@"
