#!/bin/sh
#
# ~~/.xinitrc
#
# Executed by startx (run your window manager from here)
#
LOCALE="zh_CN.UTF-8"
export XIM_PROGRAM=/usr/local/bin/fcitx
export XIM=fcitx
export XMODIFIERS=@im=fcitx
export GTK_IM_MODULE=fcitx
export QT_IM_MODULE=fcitx

xset -dpms
xset s 1800

xsetroot -cursor_name left_ptr
xsetroot -solid black
#numlockx &

case $1 in
    xmonad)
      exec xmonad
      ;;
    *)
      exec openbox-session
      ;;
esac
